name: Deploy

on: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: '@reactcalendar/components'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
